INSERT INTO passwords (user_id, organisations_id, category, url, password_text) VALUES (1, 1, 'social', 'www.facebook.com', '9873masdsa7');
INSERT INTO passwords (user_id, organisations_id, category, url, password_text) VALUES (1, 1, 'social', 'www.reddit.com', 'dlksaj87s');
INSERT INTO passwords (user_id, organisations_id, category, url, password_text) VALUES (1, 2, 'work related', 'www.worklogin.com', '9873masdsa7');
INSERT INTO passwords (user_id, organisations_id, category, url, password_text) VALUES (2, 3, 'entertainment', 'www.youtube.com', 'fkjashfjaks8');
INSERT INTO passwords (user_id, organisations_id, category, url, password_text) VALUES (2, 3, 'social', 'www.4chan.com', 'fasfhkashfkj');
INSERT INTO passwords (user_id, organisations_id, category, url, password_text) VALUES (2, 3, 'work related', 'www.worklogin2.com', '9873masdsa7');
INSERT INTO passwords (user_id, organisations_id, category, url, password_text) VALUES (3, 3, 'social', 'www.instagram.com', 'kljfasj');
INSERT INTO passwords (user_id, organisations_id, category, url, password_text) VALUES (3, 3, 'social', 'www.tweeter.com', 'dlsadasdfa');
INSERT INTO passwords (user_id, organisations_id, category, url, password_text) VALUES (3, 3, 'work related', 'www.worklogin3.com', '9fasfs');
INSERT INTO passwords (user_id, organisations_id, category, url, password_text) VALUES (4, 1, 'entertainment', 'www.disneyplus.com', 'fsafasfsafa');
INSERT INTO passwords (user_id, organisations_id, category, url, password_text) VALUES (4, 2, 'social', 'www.twitter.com', 'uiha78s68aj');
INSERT INTO passwords (user_id, organisations_id, category, url, password_text) VALUES (4, 2, 'entertainment', 'www.netflix.com', 'lhsafua');
